# Generated by Django 3.0.2 on 2020-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
