# Generated by Django 3.0.2 on 2020-01-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20200126_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='dial_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
