# Generated by Django 3.0.2 on 2020-01-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('recommended_by', models.CharField(choices=[('FR', 'Friend'), ('PS', 'Previous Student'), ('WI', 'Walk-In'), ('SA', 'Sub Agent'), ('OB', 'Other Branch')], max_length=2, null=True)),
                ('visa_type', models.CharField(choices=[('SV', 'STUDENT VISA'), ('TV', 'TOURIST VISA')], max_length=2, null=True)),
                ('type_of_lead', models.CharField(choices=[('C', 'Cold'), ('W', 'Warm'), ('H', 'Hot')], max_length=1, null=True)),
                ('month_intake', models.DateField(null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Address')),
                ('country_interested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Country')),
            ],
        ),
    ]
